baseURL = "https://blog.jesterlabs.ai"
title = "All Posts"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Jester Labs Blog"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "A blog about creative AI and dumb stuff" 

    # The description of your website. It will be displayed in the home page
    # mainpagedesc = "Blog by bois"

    # The name to display in the copyright section in the footer
    copyrightname = "Jester Labs"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://jesterlabs.ai"

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://jesterlabs.ai"       # The path can lead to a content folder too.
    weight = 20



[params.copyright]
    name = "Jester Labs"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://jesterlabs.ai"

    # Text to go before copyright information
    # prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    # suffix = "Example site"


[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true